# docker-compose.yml
version: '3'
services:
  etcd-node1:
    image: quay.io/coreos/etcd:v3.5
    environment:
      - ETCD_NAME=node1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node1:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node1:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=node1=http://etcd-node1:2380,node2=http://etcd-node2:2380,node3=http://etcd-node3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - "2379:2379"

  etcd-node2:
    image: quay.io/coreos/etcd:v3.5
    environment:
      - ETCD_NAME=node2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node2:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node2:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=node1=http://etcd-node1:2380,node2=http://etcd-node2:2380,node3=http://etcd-node3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - "2381:2379"

  etcd-node3:
    image: quay.io/coreos/etcd:v3.5
    environment:
      - ETCD_NAME=node3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node3:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node3:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=node1=http://etcd-node1:2380,node2=http://etcd-node2:2380,node3=http://etcd-node3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - "2382:2379"
